# Site
repository: arranzropablo/arranzropablo-site
favicon: images/favicon.ico

# Personal info
name: Pablo Arranz Ropero
title: Backend developer
email: arranzropablo@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: arranzropablo
github_username:  arranzropablo
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: arranzropablo
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Pablo Arranz Ropero and I'm a junior backend developer @ Zooplus. 
  Besides backend, I also enjoy learning about CI/CD and operational tools such as <mark>K8s</mark>, <mark>Docker</mark>, <mark>ELK</mark>... among others.
  Although I barely started my career I consider myself a truly capable programmer led by my effort and my endless wish of knowledge.

  My best programming skill is <mark>Java</mark> and I'm currently interested on learning <mark>Go</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
